package com.lumiamuyu.shopping.dao;

import com.lumiamuyu.shopping.pojo.Shipping;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_shipping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_shipping
     *
     * @mbggenerated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_shipping
     *
     * @mbggenerated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_shipping
     *
     * @mbggenerated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_shipping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shipping record);

    /**
     * 删除地址
     * */
    int deleteAddressByUserIdAndShoppingId(@Param("userId") Integer userId,
                                           @Param("shoppingId") Integer shoppingId);

    /**
     * 登录状态更新地址
     * */
    int updateBySelectiveKey(Shipping shipping);

    /**
     * 根据用户id查询该用户的地址列表
     * */
    List<Shipping> selectShippingListByUserId(Integer userId);

}