package com.lumiamuyu.shopping.dao;

import com.lumiamuyu.shopping.pojo.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxy_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);


    /**
     * 校验用户名
     * */
    int checkUsername(String username);

    /**
     * 根据用户名和密码查找用户信息
     * */
    User selectUserInfoByUsernameAndPassword(@Param("username") String username,
                                             @Param("password") String password);
    /**
     * 校验邮箱
     * */
    int checkEmail(String email);

    /**
     * 根据用户名查询密保问题
     * */
    String selectQuestionByUsername(String username);

    /**
     * 根据用户名，问题，答案查询记录
     * */
    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                             @Param("question") String question,
                                             @Param("answer") String answer);

    /**
     * 修改用户密码
     * */
    int updateUserPassword(@Param("username") String username,
                           @Param("password") String newPassword);

    /**
     * 根据旧密码修改为新密码
     * */
    int updatePasswordByPasswordOld(User userInfo);

    /**
     * 更新用户信息
     * */
    int updateUserBySelectActive(User userInfo);
}